[package]
name = "tenebrisnoctua/fusionfoundation"
description = "A Fusion port of Roblox's Foundation Library, to make UI components for Roblox."
version = "0.6.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["LICENSE", "Foundation", "Foundation/*", "default.project.json", "wally.toml"]

[dependencies]
